# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Google-SafeBrowsing2-Redis
version:      0.4
version_from: lib/Net/Google/SafeBrowsing2/Redis.pm
installdirs:  site
requires:
    Net::Google::SafeBrowsing2::Storage: 0.4
    Redis::hiredis:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
